FROM rust:1.85.0 AS final

WORKDIR /app

RUN useradd -m myuser

COPY Cargo.toml Cargo.lock ./

RUN cargo fetch

COPY src ./src
RUN cargo build --release

RUN chown -R myuser:myuser /app && chmod -R 770 /app

RUN apt update && apt install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

USER myuser

EXPOSE 8080

CMD ["./target/release/TP_Rust"]