FROM rust:1.85.0 AS builder

WORKDIR /TPRust

COPY Cargo.toml Cargo.lock ./

RUN cargo fetch

COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

RUN useradd -m myuser

WORKDIR /TPRust

COPY --from=builder /TPRust/target/release/TP_Rust /TPRust/TP_Rust

RUN chown -R myuser:myuser /TPRust

RUN chmod -R 770 /TPRust

RUN apt update && apt install -y curl

USER myuser

EXPOSE 8080

CMD ["/TPRust/TP_Rust"]